// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPfTtsf_u-7uBUyKSJEecKF41uCtJG0Hc',
    appId: '1:701371230730:web:103195ff9cc7e02532cdf3',
    messagingSenderId: '701371230730',
    projectId: 'chat-app-e25a8',
    authDomain: 'chat-app-e25a8.firebaseapp.com',
    storageBucket: 'chat-app-e25a8.appspot.com',
    measurementId: 'G-N16KXDXJNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhLQufeaTrGkvAP3-ILtAmB8Dume0luOg',
    appId: '1:701371230730:android:893205e8e43fae2e32cdf3',
    messagingSenderId: '701371230730',
    projectId: 'chat-app-e25a8',
    storageBucket: 'chat-app-e25a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT4QhCVHGivEQ-BBl5epV5wIH6n_AgmDE',
    appId: '1:701371230730:ios:7ddb79fc2c101edb32cdf3',
    messagingSenderId: '701371230730',
    projectId: 'chat-app-e25a8',
    storageBucket: 'chat-app-e25a8.appspot.com',
    iosClientId: '701371230730-kvr9302dnkq1vr8gj4uoi4effi6alq0s.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChatApp',
  );
}
